### ISSUE TITLE
Hexo NexT新增哈林摇特效，嗨起来😜

### ISSUE THREAD

**Issue by leafjame** [theme-next/awesome-next#10]
[链接地址](https://leafjame.github.io)
点击首页的 High~，页面开始晃动起来。。。😜
![image](https://user-images.githubusercontent.com/29299658/62913066-3fe5bc80-bdbd-11e9-9934-220547489372.png)
![image](https://user-images.githubusercontent.com/29299658/62913073-46743400-bdbd-11e9-8fef-23574c1a4b8a.png)

由于之前加的样式有点多，造成排版样式有点乱，慌的效果七零八碎😭。。。
有谁有好的优化方案

**Comment by stevenjoezhang** [comment]
拜读了一下您的文章，里面有大量直接修改swig模版的教程。这是不推荐的行为，因为这在使用`git pull`等方式更新主题时，可能会造成大量的merge conflict。您可以了解一下theme-inject特性。
