### ISSUE TITLE
Can you provide hot articles, hot reviews, latest articles in the sidebar?

### ISSUE THREAD

**Issue by znmlr** [theme-next/awesome-next#13]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
> This is just a suggestion, not a bug.  

Thank you very much for providing such a great theme!!

Most of the traditional blogs provide the 3 columns in the sidebar for the writer, especially the popular article (or the recommended article). The author can put his own good work here for everyone to read.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by stevenjoezhang** [comment]
If you still need this feature, please ask Hexo to add related helpers: https://github.com/hexojs/hexo

<blockquote><img src="https://avatars0.githubusercontent.com/u/6375567?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hexojs/hexo">hexojs/hexo</a></strong></div><div>A fast, simple & powerful blog framework, powered by Node.js. - hexojs/hexo</div></blockquote>
