### ISSUE TITLE
I wonder what the purpose of building this repo is...

### ISSUE THREAD

**Issue by sandyzikun** [theme-next/awesome-next#14]
如题（Chiglish见谅），我想知道这个repo建立的目的是什么？readme上面也没写

**Comment by 1v9** [comment]
主要是插件，一些旧的功能可能会拆分到这里，一些新的功能也可能会直接交付到这里。
我个人角度，衡量它们的标准是过于琐碎导致牵扯开发精力或者说不值得加入主题。
另外，从仓库名称的角度来说，awesome 自然欢迎一切 awesome，欢迎提交PR，比如能追上 NexT 主线的入门教程。

**Comment by sandyzikun** [comment]
谢谢谢谢，也就是说我们希望能有什么新功能可以写出来在这里申请就是啦
