### ISSUE TITLE
希望配置文件里可以更改书签位置！

### ISSUE THREAD

**Issue by suyinLoong** [theme-next/awesome-next#16]
默认书签位置在右上角，这和Follow me on github这个模块位置一样，有时候两者会重叠，如果可以将书签的位置改为左上角就完美了

**Comment by stevenjoezhang** [comment]
默认不在右上角哦，书签位置是会根据sidebar位置变的。

**Comment by stevenjoezhang** [comment]
另，请不要重复提交 Issue。
