### ISSUE TITLE
Custom page layout (gallery and product page)

### ISSUE THREAD

**Issue by maddovr** [theme-next/awesome-next#7]
It's me, again! 
I wanted to create a layout for two custom pages, one being a gallery(not a slideshow or pictures embedded on a post, but a kind like a product selection), with an animation like [this one](https://www.w3schools.com/howto/howto_css_image_overlay_slide.asp), and the second being a product page, which should have a db-like appearance like [this one](https://www.animeclick.it/manga/20675/bokutachi-wa-benkyou-ga-dekinai). How do I go about this and where would I put them in the hierarchy? Also, for the second page, is it possible to create a skeleton to fill in instead of the proper page(like, having the db stuff parsed in the front matter or something)?

**Comment by stevenjoezhang** [comment]
It seems that both pages can be implemented with the tag plugin. If this feature is added to NexT: https://github.com/theme-next/hexo-next-tag, you can create these pages manually, and edit the `menu` section in `_config.yml` to enable them.

<blockquote><img src="https://avatars3.githubusercontent.com/u/32585093?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/theme-next/hexo-next-tag">theme-next/hexo-next-tag</a></strong></div><div>Tag plugins for NexT. Contribute to theme-next/hexo-next-tag development by creating an account on GitHub.</div></blockquote>

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/theme-next/hexo-theme-next/issues/1253
